-- =============================================
-- İLK ADMİN OLUŞTURMA
-- =============================================
-- Admin oluşturma işlemi artık API üzerinden yapılıyor
-- deployment/create_admin.sh script'i backend başladıktan sonra
-- otomatik olarak admin kullanıcısını oluşturur
--
-- Email: muhammik1234@gmail.com
-- Şifre: yemekkykadmin123
-- =============================================

